### ISSUE TITLE
Improvements to the Redis connection/codec layer

### ISSUE THREAD

**Issue by tishun** [redis/lettuce#2924]
## Feature Request

This is a container issue to host all requests for improvements to the way Lettuce handles connections.

#### List of historical issues

- [ ] https://github.com/redis/lettuce/issues/622
- [ ] https://github.com/redis/lettuce/issues/632
- [ ] https://github.com/redis/lettuce/issues/1256
- [ ] https://github.com/redis/lettuce/issues/2608

#### List of new issues
